# Tips for Losing Weight

I lost 40 pounds of "COVID weight" in under a year without strenuous exercise. I did it by changing my shopping, prep/cooking, and eating habits in ways that were sustainable for long periods of time (or permanently):

-   Weekly shopping trips to build and maintain a pantry.

    -   Even a pantry with fatty foods can help cut calories, compared to eating takeout.

    -   Buy items that you can use in more than just one recipe. You should always have staplesand ingredients like salt, black pepper, cooking oil, onions, potatoes, garlic, and bouillon. If you run out, buy more -- even if you don't have a meal planned for them yet. Buying too much and throwing it out is OK -- you will course-correct, and takeout restaurants waste way more. Freeze some stuff -- compromise between freshness, cost and healthiness.
  
-   Decrease junk food. The worst are items that are high in calories but don't make you feel full (examples: potato chips and cola). Keep less junk food in your pantry. Find low-calorie alternatives to the junk food you like. For example, I replaced potato chips with popcorn (low calorie but not nutritious/filling) and cashews (high calorie but nutritious/filling).

-   Drink little or no beer. Light beer is fine in terms of calories but whats the point. A 1.5 oz shot of liquor (vodka, rum, whiskey, etc) will be less caloric a standard-sized glass of wine or beer. I typically mix my liquor of choice with diet soda when I'm trying to lose weight.

-   Aim for a calorie deficit on the majority of days each week, and a good overall deficit each week. One pound of weight loss is equivalent to a deficit of \~3500 calories -- so you need an average deficit of 500 calories / day to lose a pound per week.

-   Eat less food.

    -   If you are cooking at home, eat from a smaller plate and give yourself a smaller serving size. Eat seconds, and keep eating til you're full -- but this hack will often make you feel fuller sooner.

    -   I tried intermittent fasting. I worked a sedentary job from home, so I tried to go 6-8 hours in the middle of the day without eating. But it can cause lack of energy, "hanger", binge / disordered eating, et cetera. I'd recommend other "eat less food" strategies before this one.
